[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

remappings = [
"ds-test/=lib/forge-std/lib/ds-test/src/",
"forge-std/=lib/forge-std/src/",
"@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
"@solmate/=lib/solmate/src/",
]

auto_detect_remappings = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
